# Generated by Django 4.2.1 on 2023-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='json_data',
        ),
    ]
