# Generated by Django 4.2.1 on 2023-06-09 12:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_datamodel_remove_imagemodel_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('leadId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('fax', models.BigIntegerField()),
                ('company', models.CharField(max_length=255)),
                ('leadStatus', models.CharField(choices=[('LS1', 'New'), ('LS2', 'Assigned'), ('LS3', 'In Process'), ('LS4', 'Converted'), ('LS5', 'Recycled'), ('LS6', 'Dead')], max_length=4)),
                ('leadSource', models.CharField(choices=[('LSo1', 'Existing Customer'), ('LSo2', 'Self Generated'), ('LSo3', 'Employee'), ('LSo4', 'Converted'), ('LSo5', 'Partner'), ('LSo6', 'Public Relations'), ('LSo7', 'Other')], max_length=4)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.BigIntegerField()),
                ('createdDate', models.DateField(default=datetime.date.today)),
                ('modifiedDate', models.DateField(default=datetime.date.today)),
                ('accountName', models.CharField(max_length=255)),
                ('accountRevenue', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
