# Generated by Django 4.2.1 on 2023-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_leads_leadsource_remove_leads_leadstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='leads',
            name='leadSource',
            field=models.CharField(choices=[('LSo1', 'Existing Customer'), ('LSo2', 'Self Generated'), ('LSo3', 'Employee'), ('LSo4', 'Converted'), ('LSo5', 'Partner'), ('LSo6', 'Public Relations'), ('LSo7', 'Other')], default=2, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='leadStatus',
            field=models.CharField(choices=[('LS1', 'New'), ('LS2', 'Assigned'), ('LS3', 'In Process'), ('LS4', 'Converted'), ('LS5', 'Recycled'), ('LS6', 'Dead')], default=2, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LeadsDropDown',
        ),
    ]
