# Generated by Django 4.2.1 on 2023-06-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_leads_json_data_leads_leadsource_leads_leadstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='modifiedDate',
        ),
    ]
