# Generated by Django 4.2.1 on 2023-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_leads_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='leadStatus',
            field=models.CharField(choices=[('LS1', 'New'), ('LS2', 'Assigned'), ('LS3', 'In Process'), ('LS4', 'Converted'), ('LS5', 'Recycled'), ('LS6', 'Dead'), ('LS7', 'Choice 7'), ('LS8', 'Choice 8'), ('LS9', 'Choice 9'), ('LS10', 'Choice 10'), ('LS11', 'Choice 11'), ('LS12', 'Choice 12'), ('LS13', 'Choice 13'), ('LS14', 'Choice 14'), ('LS15', 'Choice 15'), ('LS16', 'Choice 16'), ('LS17', 'Choice 17'), ('LS18', 'Choice 18'), ('LS19', 'Choice 19'), ('LS20', 'Choice 20'), ('LS21', 'Choice 21'), ('LS22', 'Choice 22'), ('LS23', 'Choice 23'), ('LS24', 'Choice 24'), ('LS25', 'Choice 25'), ('LS26', 'Choice 26'), ('LS27', 'Choice 27'), ('LS28', 'Choice 28'), ('LS29', 'Choice 29'), ('LS30', 'Choice 30'), ('LS31', 'Choice 31'), ('LS32', 'Choice 32'), ('LS33', 'Choice 33'), ('LS34', 'Choice 34'), ('LS35', 'Choice 35'), ('LS36', 'Choice 36'), ('LS37', 'Choice 37'), ('LS38', 'Choice 38'), ('LS39', 'Choice 39'), ('LS40', 'Choice 40'), ('LS41', 'Choice 41'), ('LS42', 'Choice 42'), ('LS43', 'Choice 43'), ('LS44', 'Choice 44'), ('LS45', 'Choice 45'), ('LS46', 'Choice 46'), ('LS47', 'Choice 47'), ('LS48', 'Choice 48'), ('LS49', 'Choice 49'), ('LS50', 'Choice 50')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
