# Generated by Django 4.2.1 on 2023-06-15 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_lead_delete_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('json_data', models.JSONField(default=dict)),
                ('accountId', models.IntegerField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=255)),
                ('accountType', models.CharField(choices=[('AT1', 'Analyst'), ('AT2', 'Competitor'), ('AT3', 'Customer'), ('AT4', 'Investor'), ('AT5', 'Partner')], max_length=5)),
                ('accountNumber', models.BigIntegerField()),
                ('industry', models.CharField(choices=[('I1', 'Apparel'), ('I2', 'Banking'), ('I3', 'Environmental'), ('I4', 'Finance'), ('I5', 'Health Care')], max_length=5)),
                ('website', models.CharField(max_length=255)),
                ('tickerSymbol', models.CharField(max_length=255)),
                ('phoneNumber', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('billingAddress', models.CharField(max_length=255)),
                ('shippingAddress', models.CharField(max_length=255)),
                ('sicCode', models.BigIntegerField()),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('modifiedDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
        migrations.AlterField(
            model_name='lead',
            name='leadId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
