# Generated by Django 4.2.1 on 2023-06-15 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_accounts_remove_lead_id_alter_lead_leadid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('json_data', models.JSONField(default=dict)),
                ('opportunityId', models.IntegerField(primary_key=True, serialize=False)),
                ('opportunityName', models.CharField(max_length=255)),
                ('opportunityType', models.CharField(choices=[('EB1', 'Existing Business'), ('EB2', 'New Business')], max_length=10)),
                ('leadSource', models.CharField(choices=[('LSo1', 'Existing Customer'), ('LSo2', 'Self Generated'), ('LSo3', 'Employee'), ('LSo4', 'Converted'), ('LSo5', 'Partner'), ('LSo6', 'Public Relations'), ('LSo7', 'Other')], max_length=5)),
                ('amount', models.FloatField()),
                ('stage', models.CharField(choices=[('S1', 'Prospecting'), ('S2', 'Qualification'), ('S3', 'Needs Analysis'), ('S4', 'Value Proposition'), ('S5', 'Identify Decision Makers')], max_length=10)),
                ('expectedCloseDate', models.DateField()),
                ('probability', models.CharField(max_length=255)),
                ('createdDate', models.DateField(default=datetime.date.today)),
                ('modifiedDate', models.DateField(default=datetime.date.today)),
                ('accountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.accounts')),
                ('leadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.lead')),
            ],
            options={
                'verbose_name_plural': 'Oppurtunity',
            },
        ),
    ]
