# Generated by Django 4.2.1 on 2023-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_opportunities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('json_data', models.JSONField(default=dict)),
                ('taskId', models.IntegerField(primary_key=True, serialize=False)),
                ('taskName', models.TextField(blank=True)),
                ('accountId', models.IntegerField(blank=True, null=True)),
                ('opportunityId', models.IntegerField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ST1', 'Not Started'), ('ST2', 'In Progress'), ('ST3', 'Completed'), ('ST4', 'Pending Input'), ('ST5', 'Deferred')], max_length=10, null=True)),
                ('priority', models.CharField(blank=True, choices=[('P1', 'High'), ('P2', 'Medium'), ('P3', 'Low')], max_length=10, null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('modifiedDate', models.DateField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='task_profile_pics/')),
            ],
            options={
                'verbose_name_plural': 'Task',
            },
        ),
    ]
