# Generated by Django 4.2.1 on 2023-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(default=dict)),
                ('reportId', models.IntegerField()),
                ('reportName', models.TextField(blank=True, null=True)),
                ('accountId', models.IntegerField(blank=True, null=True)),
                ('opportunityId', models.IntegerField(blank=True, null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('modifiedDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
    ]
