# Generated by Django 4.2.1 on 2023-06-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accountId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.accounts'),
        ),
        migrations.AlterField(
            model_name='report',
            name='opportunityId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.opportunities'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accountId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.accounts'),
        ),
        migrations.AlterField(
            model_name='task',
            name='opportunityId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.opportunities'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(default=dict)),
                ('noteId', models.IntegerField()),
                ('noteType', models.CharField(choices=[('N1', 'note1'), ('N2', 'note2'), ('N3', 'note3')], max_length=4)),
                ('name', models.TextField(blank=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='notes_profile_photos/')),
                ('accountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.accounts')),
                ('opportunityId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.opportunities')),
            ],
            options={
                'verbose_name_plural': 'Note',
            },
        ),
    ]
