# Generated by Django 4.2.1 on 2023-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_report_accountid_alter_report_opportunityid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
