# Generated by Django 4.2.1 on 2023-06-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_dropdownmodel_delete_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='annualRevenue',
            new_name='accountRevenue',
        ),
    ]
