# Generated by Django 4.2.1 on 2023-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_rename_annualrevenue_lead_accountrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='opportunityType',
            field=models.CharField(choices=[('OT1', 'Existing Business'), ('OT2', 'New Business')], max_length=10),
        ),
    ]
