# Generated by Django 4.2.1 on 2023-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_opportunities_opportunitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_photos/'),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='expectedCloseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='leadSource',
            field=models.CharField(blank=True, choices=[('LSo1', 'Existing Customer'), ('LSo2', 'Self Generated'), ('LSo3', 'Employee'), ('LSo4', 'Converted'), ('LSo5', 'Partner'), ('LSo6', 'Public Relations'), ('LSo7', 'Other')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='modifiedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='opportunityName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='opportunityType',
            field=models.CharField(blank=True, choices=[('OT1', 'Type 1'), ('OT2', 'Type 2'), ('OT3', 'Type 3')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='stage',
            field=models.CharField(blank=True, choices=[('S1', 'Stage 1'), ('S2', 'Stage 2'), ('S3', 'Stage 3'), ('S4', 'Stage 4'), ('S5', 'Stage 5')], max_length=2, null=True),
        ),
    ]
