# Generated by Django 4.2.1 on 2023-06-16 05:32

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_opportunities_profilephoto_and_more'),
    ]


