# Generated by Django 4.2.1 on 2023-06-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_alter_opportunities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunities',
            options={'verbose_name_plural': 'Opportunity'},
        ),
    ]
