# Generated by Django 4.2.1 on 2023-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_remove_notes_id_remove_report_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunities',
            options={},
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
