# Generated by Django 4.2.1 on 2023-06-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_alter_opportunities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunities',
            options={'verbose_name_plural': 'Opportunities'},
        ),
    ]
