# Generated by Django 4.2.1 on 2023-06-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_alter_opportunities_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='opportunities',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='json_data',
        ),
    ]
