# Generated by Django 4.2.1 on 2023-06-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_remove_accounts_json_data_remove_notes_json_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='json_data',
        ),
    ]
