# Generated by Django 4.2.1 on 2023-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_remove_lead_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordo_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedTo', models.CharField(default='admin', max_length=50)),
                ('chartType', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('doughnut', 'Doughnut'), ('pie', 'Pie')], max_length=50)),
                ('description', models.TextField()),
                ('fields', models.JSONField(default=list)),
                ('groupByField', models.CharField(max_length=50)),
                ('groupByLabel', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('primaryModule', models.CharField(max_length=50)),
                ('summaryField', models.CharField(max_length=50)),
                ('summaryLabel', models.CharField(max_length=50)),
                ('sortBy', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='accountRevenue',
            new_name='annualRevenue',
        ),
    ]
