# Generated by Django 4.2.1 on 2023-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_remove_lead_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='accountRevenue',
            new_name='annualRevenue',
        ),
    ]
