# Generated by Django 4.2.1 on 2023-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_ordo_report_rename_accountrevenue_lead_annualrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordo_report',
            name='sortOrder',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
