# Generated by Django 4.2.1 on 2023-06-30 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_rename_accountrevenue_lead_annualrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioReport',
            fields=[
                ('reportId', models.IntegerField(primary_key=True, serialize=False)),
                ('reportName', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('modifiedDate', models.DateField(blank=True, null=True)),
                ('audioFile', models.FileField(blank=True, null=True, upload_to='audio_reports/')),
                ('accountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.accounts')),
                ('opportunityId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.opportunities')),
            ],
            options={
                'verbose_name_plural': 'Audio Reports',
            },
        ),
    ]
