# Generated by Django 4.2.1 on 2023-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_ordo_report_sortorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordo_report',
            name='sortBy',
            field=models.CharField(choices=[('createdDate', 'createdDate'), ('modifiedDate', 'modifiedDate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordo_report',
            name='sortOrder',
            field=models.CharField(choices=[('asc', 'Ascending'), ('dsc', 'Descending')], max_length=50),
        ),
    ]
