# Generated by Django 4.2.1 on 2023-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_alter_ordo_report_sortby_alter_ordo_report_sortorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordo_report',
            name='sortOrder',
            field=models.CharField(choices=[('ASC', 'Ascending'), ('DSC', 'Descending')], max_length=50),
        ),
    ]
