# Generated by Django 4.2.1 on 2023-07-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='createUser',
        ),
    ]
